### ISSUE TITLE
Not working with Google Chrome beta 62.0.3202.18

### ISSUE THREAD

**Issue by solispauwels** [giggio/node-chromedriver#121]
Uncaught WebDriverError: disconnected: unable to connect to renderer
  (Session info: chrome=62.0.3202.18)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 3.16.0-44-generic x86_64)
      at WebDriverError (node_modules/selenium-webdriver/lib/error.js:27:5)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:529:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:109:7)
  From: Task: WebDriver.manage().window().setSize(650, 960)
      at browsers.(anonymous function).then.driver (lib/driverFactory.js:48:34)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3092:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3075:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7

**Comment by giggio** [comment]
If Chromedriver is not working with the beta Chrome you should report the error to the Chromedriver project, this is only a wrapper to help install and run it.

**Comment by fippo** [comment]
I ran into the same issue and it only happened when calling
`driver.manage().window().setSize(1280, 1024);`
immediately after calling build()

Maybe this helps.

**Comment by solispauwels** [comment]
Yeah, that is what is happen for me, but this is a bug anyway. how to resize chrome then?

**Comment by solispauwels** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1918

**Comment by solispauwels** [comment]
Can you release the 2.33 version?

**Comment by giggio** [comment]
2.33 is not out yet. http://chromedriver.storage.googleapis.com/index.html

**Comment by ballwood** [comment]
@giggio http://chromedriver.storage.googleapis.com/index.html?path=2.33/ think its up now

**Comment by mauricioardiles-ml** [comment]
@giggio 2.33 was released yesterday, greetings

**Comment by giggio** [comment]
2.33 is now published to npm.
