### ISSUE TITLE
support selenium v4.x?

### ISSUE THREAD

**Issue by crapthings** [giggio/node-chromedriver#142]
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

working

"chromedriver": "^2.35.0",
"selenium-webdriver": "^3.6.0"

failed

"chromedriver": "^2.35.0",
"selenium-webdriver": "^v4.0.0-alpha.1"

```
=> App running at: http://localhost:3000/
    ✓ should be true95(8)?
I20180227-15:36:58.495(8)?
I20180227-15:36:58.495(8)?
I20180227-15:36:58.495(8)?   1 passing (15ms)
I20180227-15:36:58.495(8)?
I20180227-15:36:58.495(8)?
I20180227-15:36:58.496(8)? --------------------------------
I20180227-15:36:58.496(8)? ----- RUNNING CLIENT TESTS -----
I20180227-15:36:58.496(8)? --------------------------------
W20180227-15:36:58.579(8)? (STDERR) meteor://💻app/packages/meteortesting_browser-tests.js:133
W20180227-15:36:58.579(8)? (STDERR)   driver.manage().window().setPosition(20000, 20000); // We periodically grab logs from Chrome and pass them back.
W20180227-15:36:58.580(8)? (STDERR)                            ^
W20180227-15:36:58.580(8)? (STDERR)
W20180227-15:36:58.580(8)? (STDERR) TypeError: driver.manage(...).window(...).setPosition is not a function
W20180227-15:36:58.580(8)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:45:28)
W20180227-15:36:58.580(8)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:22:7)
W20180227-15:36:58.581(8)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:120:3)
W20180227-15:36:58.581(8)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:145:7)
W20180227-15:36:58.581(8)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:100:13)
W20180227-15:36:58.581(8)? (STDERR)     at done (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
W20180227-15:36:58.581(8)? (STDERR)     at Runner.<anonymous> (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
W20180227-15:36:58.582(8)? (STDERR)     at emitNone (events.js:111:20)
W20180227-15:36:58.582(8)? (STDERR)     at Runner.emit (events.js:208:7)
W20180227-15:36:58.582(8)? (STDERR)     at /Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
W20180227-15:36:58.582(8)? (STDERR)     at /Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:644:9
W20180227-15:36:58.582(8)? (STDERR)     at next (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:284:14)
W20180227-15:36:58.582(8)? (STDERR)     at Immediate._onImmediate (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:320:5)
W20180227-15:36:58.583(8)? (STDERR)     at runCallback (timers.js:789:20)
W20180227-15:36:58.583(8)? (STDERR)     at tryOnImmediate (timers.js:751:5)
W20180227-15:36:58.583(8)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-test-and-ci@ test: `TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-test-and-ci@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/monsterstep/.npm/_logs/2018-02-27T07_36_58_731Z-debug.log

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4 took 15s
👽 meteor npm run test

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4
👽 meteor npm i
updated 1 package in 3.951s

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4 took 5s
👽 meteor run test
Unknown run target: test

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4
👽 metepr npm run test
zsh: command not found: metepr

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4
👽 l
total 144
drwxr-xr-x    8 monsterstep  staff   256B Feb 27 15:46 .
drwxr-xr-x   12 monsterstep  staff   384B Feb 27 15:21 ..
-rw-r--r--    1 monsterstep  staff    13B Feb 27 15:21 .gitignore
drwxr-xr-x   10 monsterstep  staff   320B Feb 27 15:23 .meteor
-rw-r--r--    1 monsterstep  staff   151B Feb 27 15:28 app.tests.js
drwxr-xr-x  118 monsterstep  staff   3.7K Feb 27 15:46 node_modules
-rw-r--r--    1 monsterstep  staff    58K Feb 27 15:46 package-lock.json
-rw-r--r--    1 monsterstep  staff   494B Feb 27 15:46 package.json

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4
👽 meteor npm run test

> meteor-test-and-ci@ test /Users/monsterstep/dev/sandbox-experimentals/meteor/meteor-test-and-ci
> TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
I20180227-15:47:53.506(8)?
I20180227-15:47:53.538(8)? --------------------------------
I20180227-15:47:53.539(8)? ----- RUNNING SERVER TESTS -----
I20180227-15:47:53.539(8)? --------------------------------
I20180227-15:47:53.539(8)?
I20180227-15:47:53.539(8)?
I20180227-15:47:53.539(8)?
I20180227-15:47:53.540(8)?   something to be true
=> Started your app.

=> App running at: http://localhost:3000/
    ✓ should be true40(8)?
I20180227-15:47:53.541(8)?
I20180227-15:47:53.541(8)?
I20180227-15:47:53.541(8)?   1 passing (13ms)
I20180227-15:47:53.541(8)?
I20180227-15:47:53.541(8)?
I20180227-15:47:53.541(8)? --------------------------------
I20180227-15:47:53.541(8)? ----- RUNNING CLIENT TESTS -----
I20180227-15:47:53.542(8)? --------------------------------
I20180227-15:47:54.817(8)?
I20180227-15:47:54.817(8)?
I20180227-15:47:54.817(8)?   something to be true
I20180227-15:47:54.817(8)?     ✓ should be true
I20180227-15:47:54.818(8)?
I20180227-15:47:54.818(8)?
I20180227-15:47:54.818(8)?   1 passing (11ms)
I20180227-15:47:54.818(8)?
I20180227-15:47:54.830(8)? [ERROR] http://localhost:3000/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)
I20180227-15:47:54.891(8)? All tests finished!
I20180227-15:47:54.891(8)?
I20180227-15:47:54.891(8)? --------------------------------
I20180227-15:47:54.891(8)? SERVER FAILURES: 0
I20180227-15:47:54.892(8)? CLIENT FAILURES: 0
I20180227-15:47:54.892(8)? --------------------------------

sandbox-experimentals/meteor/meteor-test-and-ci on  master [?] is 📦  ⚠ via ⬢ v8.9.4 took 17s
```

**Comment by giggio** [comment]
This is a problem with chromedriver itself, this package only installs it.
