### ISSUE TITLE
Unable to install version 2.36.0 on ubuntu

### ISSUE THREAD

**Issue by lilianaziolek** [giggio/node-chromedriver#147]
I have a small CI server on ubuntu on which I'm trying to build latest version of my app, where I'm adding a vue-cli support, including chromedriver (including this as context in case it's some kind of inter-dependency).
It works fine when run on my Windows dev box, but fails to install chromedriver on this ubuntu instance.
I'm not really very familiar with npm but I've run the full build as well as separate attempt to install chromedriver and both fail.
This is the (end of) result for standalone npm i -g chromedriver.
Can someone tell me where to look further, or how to fix it - I can't see any other logs that would explain why this fails...
Thank you!

2731 silly install chromedriver@2.36.0
2732 info lifecycle chromedriver@2.36.0~install: chromedriver@2.36.0
2733 verbose lifecycle chromedriver@2.36.0~install: unsafe-perm in lifecycle false
2734 verbose lifecycle chromedriver@2.36.0~install: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/lib/node_modules/chromedriver/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
2735 verbose lifecycle chromedriver@2.36.0~install: CWD: /usr/lib/node_modules/chromedriver
2736 silly lifecycle chromedriver@2.36.0~install: Args: [ '-c', 'node install.js' ]
2737 silly lifecycle chromedriver@2.36.0~install: Returned: code: 1  signal: null
2738 info lifecycle chromedriver@2.36.0~install: Failed to exec install script
2739 verbose unlock done using /home/lilith/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
2740 verbose stack Error: chromedriver@2.36.0 install: `node install.js`
2740 verbose stack Exit status 1
2740 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
2740 verbose stack     at emitTwo (events.js:126:13)
2740 verbose stack     at EventEmitter.emit (events.js:214:7)
2740 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2740 verbose stack     at emitTwo (events.js:126:13)
2740 verbose stack     at ChildProcess.emit (events.js:214:7)
2740 verbose stack     at maybeClose (internal/child_process.js:925:16)
2740 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2741 verbose pkgid chromedriver@2.36.0
2742 verbose cwd /home/lilith
2743 verbose Linux 4.13.0-32-generic
2744 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "chromedriver"
2745 verbose node v8.10.0
2746 verbose npm  v5.7.1
2747 error code ELIFECYCLE
2748 error errno 1
2749 error chromedriver@2.36.0 install: `node install.js`
2749 error Exit status 1
2750 error Failed at the chromedriver@2.36.0 install script.
2750 error This is probably not a problem with npm. There is likely additional logging output above.
2751 verbose exit [ 1, true ]

**Comment by lilianaziolek** [comment]
Okay, I think I may have found the problem - I'm on a 32 bit system. A shame that the error message about it for some reason is not part of this log, but after a few more kicks  / cleans of directories / caches etc. it did come up in one of my attempts. Leaving it here in case anybody else experiences issues, but will close the issue now.
