### ISSUE TITLE
Cannot install on Amazon Linux (node:argon) due to syntax error in debug module

### ISSUE THREAD

**Issue by squallstar** [giggio/node-chromedriver#182]
I'm providing here the stack trace from our AWS machines when running `npm install`:

```
  > chromedriver@2.43.1 install /usr/src/node_modules/chromedriver
  > node install.js
  
  [91m/usr/src/node_modules/chromedriver/node_modules/tcp-port-used/node_modules/debug/src/node.js:132
  	let val = process.env[key];
  	^^^
  
  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
      at exports.runInThisContext (vm.js:53:16)
      at Module._compile (module.js:373:25)
      at Object.Module._extensions..js (module.js:416:10)
      at Module.load (module.js:343:32)
      at Function.Module._load (module.js:300:12)
      at Module.require (module.js:353:17)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (/usr/src/node_modules/chromedriver/node_modules/tcp-port-used/node_modules/debug/src/index.js:9:19)
      at Module._compile (module.js:409:26)
      at Object.Module._extensions..js (module.js:416:10)
```

This might be relevant https://github.com/visionmedia/debug/issues/611

**Comment by squallstar** [comment]
Most likely it's about updating the `` lib to 1.0.1 to get [this](https://github.com/stdarg/tcp-port-used/commit/01fb85060533a47f0d3913974d19503c9bef68dd) commit which bumps `debug` to version `4.1.0` from this PR https://github.com/stdarg/tcp-port-used/issues/3

**Comment by squallstar** [comment]
Ok so I think the issue is that suddenly there was a bump in the node version (because of `debug`), I might be able to fix this myself by upgrading Node. I'll make sure to test this asap and close the ticket if no action is required.
