### ISSUE TITLE
Fails to connect to Chrome

### ISSUE THREAD

**Issue by Cosm0** [giggio/node-chromedriver#195]
With the latest chrome (73.0.3683) chromedriver fails to connect with Chrome on tests startup on some Linux machines when tests are run inside Docker container. It works perfectly fine when run on host machine and only fails on some machines inside docker container. Reverting to older chrome version (72.0.3626) solves this issue.

Ubuntu (I see no pattern with OS versions):
     16.04.1 - succeeded, 
     16.04.2 - failed
     18.04.2 - succeeded

Docker version 18.09.3, build 774a1f4

Below exception is thrown:

WebDriverError: chrome not reachable
      (Session info: headless chrome=73.0.3683.75)
      (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-83-generic x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:585:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:533:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    WebDriverError: chrome not reachable
      (Session info: headless chrome=73.0.3683.75)
      (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-83-generic x86_64)
        at Object.checkLegacyResponse (/e2e/node_modules/selenium-webdriver/lib/error.js:585:15)
        at parseHttpResponse (/e2e/node_modules/selenium-webdriver/lib/http.js:533:13)
        at Executor.execute (/e2e/node_modules/selenium-webdriver/lib/http.js:468:26)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by jnizet** [comment]
I have the same issue on the `circleci/node:10-browsers` docker image: all my builds fail since the image uses the latest chrome (73.0.3683) (i.e. since this morning)

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
