### ISSUE TITLE
npm install chromedriver@^80.0.0 fails but npm install chromedriver@80.0.0 install the driver

### ISSUE THREAD

**Issue by vasu512** [giggio/node-chromedriver#252]
Hi, we are getting a strange situation with install chromedriver.  
below are the logs.
 **npm install chromedriver@80.0.0**
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> chromedriver@80.0.0 install /opt/temp/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
Saving to file: /tmp/80.0.3987.16/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3920K...
Received 4704K...
Received 4826K total.
Extracting zip contents
Copying to target path /opt/temp/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /opt/temp/node_modules/chromedriver/lib/chromedriver/chromedriver
npm WARN saveError ENOENT: no such file or directory, open '/opt/temp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/opt/temp/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

+ chromedriver@80.0.0
added 60 packages from 60 contributors and updated 1 package in 3.664s

**When we try to install as npm install chromedriver@^80.0.0 we are getting below error
npm install chromedriver@^80.0.0**

> chromedriver@80.0.1 install /opt/temp/node_modules/chromedriver
> node install.js

Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
Saving to file: /tmp/80.0.3987.16/chromedriver/chromedriver_linux64.zip
Error status code: 500
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>

<head>
.....
......

<table class="contentTable">
  <tr>
    <td class="contentData">
      The SSL handshake could not be performed.
    </td>
  </tr>
</table>

<table class="infoTable">
  <tr>
    <td class="infoData">
      <b>Host: </b>chromedriver.storage.googleapis.com<br />
      <b>Reason: </b>Can&apos;t initialize server context:handshakefailed:server state 1:state 9:Application response 500 handshakefailed
    </td>
  </tr>
</table>

......

</html>

npm WARN saveError ENOENT: no such file or directory, open '/opt/temp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/opt/temp/package.json'
npm WARN temp No description
npm WARN temp No repository field.
npm WARN temp No README data
npm WARN temp No license field.

+ chromedriver@80.0.1
added 78 packages from 94 contributors in 3.18s

**Comment by giggio** [comment]
I can't repro it. Can you try to manually debug the install.js file?

**Comment by vasu512** [comment]
I see that the Download URL on my machine is turning out to be this "https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip" and I have used the axios package to get the file as below and get the same 500 error

To reprodue , create a `temp.js` and run the js file as `node temp.js`
```
const axios = require('axios');

// Make a request for a user with a given ID
axios.get('https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip')
  .then(function (response) {
    // handle success
    console.log(response);
  })
  .catch(function (error) {
    // handle error
    console.log(error);
  })
  .finally(function () {
    // always executed
  });
```

The output I am getting on running temp.js is below

```
{ Error: Request failed with status code 500
    at createError (D:\project\chrome\node_modules\axios\lib\core\createError.js:16:15)
    at settle (D:\project\chrome\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (D:\project\chrome\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { url:
      'https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.19.2',
        host: 'chromedriver.storage.googleapis.com' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'www-proxy-hqdc.us.oracle.com',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 4,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'www-proxy-hqdc.us.oracle.com',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 4,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _header:
      'GET https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.2\r\nhost: chromedriver.storage.googleapis.com\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      'https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'handshakefailed',
        client: [Socket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'http://www-proxy-hqdc.us.oracle.com:80/https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'http://www-proxy-hqdc.us.oracle.com:80/https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response:
   { status: 500,
     statusText: 'handshakefailed',
     headers:
      { via: '1.1 10.68.69.7 (McAfee Web Gateway 7.8.2.13.0.30003)',
        'content-type': 'text/html',
        'cache-control': 'no-cache',
        'content-length': '2739',
        'x-frame-options': 'deny',
        'proxy-connection': 'Close' },
     config:
      { url:
         'https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip',
        method: 'get',
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'GET https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.2\r\nhost: chromedriver.storage.googleapis.com\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         'https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html>\n<!-- FileName: index.html\n     Language: [en]\n-->\n<!--Head-->\n<head>\n  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">\n  <meta http-equiv="X-UA-Compatible" content="IE=7" />\n  <title>McAfee Web Gateway - Notification</title>\n  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>\n  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />\n</head>\n<!--/Head-->\n<!--Body-->\n<body onload="swOnLoad();">\n  <table class=\'bodyTable\'>\n    <tr>\n      <td class=\'bodyData\' background=\'/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif\'>\n<!--Logo-->\n<table class=\'logoTable\'>\n  <tr>\n    <td class=\'logoData\'>\n      <a href=\'http://www.mcafee.com\'>\n        <img src=\'/mwg-internal/de5fs23hu73ds/files/default/img/oralogo-small.gif\'></a>\n    </td>\n  </tr>\n</table>\n<!--/Logo-->\n<!--Contents-->\n<!-- FileName: handshakefailed.html\n     Language: [en]\n-->\n<!--Title-->\n<table class=\'titleTable\' background=\'/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg\'>\n  <tr>\n    <td class=\'titleData\'>\n      Handshake failed\n    </td>\n  </tr>\n</table>\n<!--/Title-->\n\n<!--Content-->\n<table class="contentTable">\n  <tr>\n    <td class="contentData">\n      The SSL handshake could not be performed.\n    </td>\n  </tr>\n</table>\n<!--/Content-->\n\n<!--Info-->\n<table class="infoTable">\n  <tr>\n    <td class="infoData">\n      <b>Host: </b>chromedriver.storage.googleapis.com<br />\n      <b>Reason: </b>Can&apos;t initialize server context:handshakefailed:server state 1:state 9:Application response 500 handshakefailed\n    </td>\n  </tr>\n</table>\n<!--/Info-->\n\n<!--/Contents-->\n<!--Policy-->\n<table class=\'policyTable\'>\n  <tr>\n    <td class=\'policyHeading\'>\n      <hr>\n\n    </td>\n  </tr>\n  <tr>\n    <td class=\'policyData\'>\nIf you believe you have received this page in error, please submit an <a href="https://myhelp.oracle.com/app/answers/answer_view_GA/a_id/94/loc/en_US/g_id/141">Oracle MyHelp \nTicket</a>. If this is an urgent, service impacting issue, please contact the Global Service Desk via telephone: Dial **600\nOr Local in-country numbers can be found at <a href="http://my.oracle.com/site/git/1591/2666/index.html">Global Service Desk - Contact Numbers\n\n</p>\n    </td>\n  </tr>\n</table>\n<!--/Policy-->\n<!--Foot-->\n<table class=\'footTable\'>\n<hr>\n  <tr>\n    <td class=\'footData\'>\n      generated <span id="time">2020-03-04 12:33:59</span> by hqdc-proxy-mwg04.us.oracle.com\n    </td>\n  </tr>\n</table>\n<!--/Foot-->\n      </td>\n    </tr>\n  </table>\n</body>\n<!--/Body-->\n<!-- BLOCKBLOCK_ORACLEPROXY_BLOCKBLOCK -->\n</html>\n' },
  isAxiosError: true,
  toJSON: [Function] }
```

**Comment by vasu512** [comment]
I have also noticed the install.js file which I get when I run `npm install --save-dev chromedriver@80.0.0`(not without caret). I do not see **axios** library being used. I see **request**  being used.

**Comment by byang183** [comment]
The change for using axios is fail the installation due to this existing issue from axios:
https://github.com/axios/axios/issues/925

Need some adjustment from how axios has been used here if proxy config exists

**Comment by byang183** [comment]
In our case, the error code is 400

**Comment by vasu512** [comment]
> The change for using axios is fail the installation due to this existing issue from axios:
> [axios/axios#925](https://github.com/axios/axios/issues/925)
> 
> Need some adjustment from how axios has been used here if proxy config exists

Any update on when this can be fixed? We are now having a work around to use fixed version in our package.json of 80.0.0

**Comment by giggio** [comment]
It seems this is a problem with Axios, the updated issue seems to be this: https://github.com/axios/axios/issues/2072
Until it is fixed, what do you suggest? Can you send a minimal PR to get it to work?

**Comment by BubbleBear** [comment]
you must have proxy setting in `.npmrc`, and it caused target url to be `http://www-proxy-hqdc.us.oracle.com:80/https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip`, which doesn't seem to be legal.
i do think this is a `node-chromedriver` bug for it doesn't use proxy settings in `.npmrc` wisely.

**Comment by giggio** [comment]
I don't see how it could be set to this value. The download url is set in this line:

https://github.com/giggio/node-chromedriver/blob/16151de4c7bd87ef952665deb95aa56ce3539948/install.js#L105

And not touched after this line.
If the url is being incorrectly concatenated, it can only be Axios doing it.

You can clearly see on the logs posted on the first comment, that the url is correct:

````
Downloading from file:  https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_linux64.zip
````

So, again, can you suggest a fix that does not involve replacing Axios? Can you send a PR?

**Comment by vasu512** [comment]
> you must have proxy setting in `.npmrc`, and it caused target url to be `http://www-proxy-hqdc.us.oracle.com:80/https://chromedriver.storage.googleapis.com/80.0.3987.16/chromedriver_win32.zip`, which doesn't seem to be legal.
> i do think this is a `node-chromedriver` bug for it doesn't use proxy settings in `.npmrc` wisely.
> 
> if you are somewhere like china where google is blocked, try set `http_proxy` and `https_proxy` instead of putting it in `.npmrc`.

We will be needing the proxy settings in .npmrc for our internal artifactory repo usage. we cannot get away with proxy settings. Is there any workaround for getting the latest 81.* version of chromedirver as we now have our chrome browser at 81.*

**Comment by giggio** [comment]
@vasu512 yes: https://github.com/giggio/node-chromedriver#versioning
