### ISSUE TITLE
ChromeDriver Not Installing 

### ISSUE THREAD

**Issue by rizzlinux1388** [giggio/node-chromedriver#266]
Hello, I posted on the webdriverio glitter channel and was asked to post this here. Sorry if it's a duplicate.

When I run ```npx wdio config -y``` I get this error
```

$ npx wdio config -y
--
  |  
  | =========================
  | WDIO Configuration Helper
  | =========================
  |  
  |  
  | Installing wdio packages:
  | - @wdio/local-runner
  | - @wdio/mocha-framework
  | - @wdio/spec-reporter
  | - wdio-chromedriver-service
  | - @wdio/sync
  | - chromedriver
  | npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
  |  
  | > chromedriver@81.0.0 install /Users/USER/Projects/SalesForce/Webdriver.io_Scratch_org_Helper/webdriverio-test/node_modules/chromedriver
  | > node install.js
  |  
  | ChromeDriver binary exists. Validating...
  | (node:29522) ExperimentalWarning: The fs.promises API is experimental
  | Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
  | Downloading from file:  https://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_mac64.zip
  | Saving to file: /var/folders/nx/zjt_3dfn2v9bychfggw6ns8c0000gn/T/81.0.4044.69/chromedriver/chromedriver_mac64.zip
  | Received 1040K...
  | Received 2080K...
  | Received 3120K...
  | Received 4160K...
  | Received 5200K...
  | Received 6240K...
  | Received 6854K total.
  | Extracting zip contents.
  | ChromeDriver installation failed Error: Error extracting archive: Error: EEXIST: file already exists, mkdir '/var/folders/nx/zjt_3dfn2v9bychfggw6ns8c0000gn/T/81.0.4044.69/chromedriver'
  | at extractDownload (/Users/USER/Projects/SalesForce/Webdriver.io_Scratch_org_Helper/webdriverio-test/node_modules/chromedriver/install.js:282:11)
  | npm WARN @wdio/spec-reporter@6.0.16 requires a peer of @wdio/cli@^6.0.1 but none is installed. You must install peer dependencies yourself.
  | npm WARN @wdio/local-runner@6.1.2 requires a peer of @wdio/cli@^6.0.1 but none is installed. You must install peer dependencies yourself.
  | npm WARN @wdio/mocha-framework@6.1.0 requires a peer of webdriverio@^6.0.1 but none is installed. You must install peer dependencies yourself.
  | npm WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
  | npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
  | npm WARN webdriverio-test@1.0.0 No description
  | npm WARN webdriverio-test@1.0.0 No repository field.
  |  
  | npm ERR! code ELIFECYCLE
  | npm ERR! errno 1
  | npm ERR! chromedriver@81.0.0 install: `node install.js`
  | npm ERR! Exit status 1
  | npm ERR!
  | npm ERR! Failed at the chromedriver@81.0.0 install script.
  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  |  
  | npm ERR! A complete log of this run can be found in:
  | npm ERR!     /Users/USER/.npm/_logs/2020-04-22T20_43_02_224Z-debug.log
  | wdio config
  |  
  | Initialize WebdriverIO and setup configuration in your current project.
  |  
  | Options:
  | --version             Show version number                            [boolean]
  | --watch               Run WebdriverIO in watch mode                  [boolean]
  | --hostname, -h        automation driver host address                  [string]
  | --port, -p            automation driver port                          [number]
  | --path                path to WebDriver endpoints (default "/")       [string]
  | --user, -u            username if using a cloud service as automation backend
  | [string]
  | --key, -k             corresponding access key to the user            [string]
  | --logLevel, -l        level of logging verbosity
  | [choices: "trace", "debug", "info", "warn", "error", "silent"]
  | --bail                stop test runner after specific amount of tests have
  | failed                                          [number]
  | --baseUrl             shorten url command calls by setting a base url [string]
  | --waitforTimeout, -w  timeout for all waitForXXX commands             [number]
  | --framework, -f       defines the framework (Mocha, Jasmine or Cucumber) to
  | run the specs                                   [string]
  | --reporters, -r       reporters to print out the results on stdout     [array]
  | --suite               overwrites the specs attribute and runs the defined
  | suite                                            [array]
  | --spec                run only a certain spec file - overrides specs piped
  | from stdin                                       [array]
  | --exclude             exclude certain spec file from the test run - overrides
  | exclude piped from stdin                         [array]
  | --mochaOpts           Mocha options
  | --jasmineNodeOpts     Jasmine options
  | --cucumberOpts        Cucumber options
  | --yarn                Install packages via yarn package manager.
  | [boolean] [default: false]
  | --yes, -y             will fill in all config defaults without prompting
  | [boolean] [default: false]
  | --help                Show help                                      [boolean]
  |  
  | Documentation: https://webdriver.io
  | @wdio/cli (v6.0.0)
  |  
  | Error: something went wrong during setup: null
  | at runConfig (/Users/USER/Projects/SalesForce/Webdriver.io_Scratch_org_Helper/webdriverio-test/node_modules/@wdio/cli/build/commands/config.js:79:11)
  | at process._tickCallback (internal/process/next_tick.js:68:7)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
  | at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
  | at Object.handler (/Users/USER/Projects/SalesForce/Webdriver.io_Scratch_org_Helper/webdriverio-test/node_modules/@wdio/cli/build/commands/config.js:118:11)
  | at process._tickCallback (internal/process/next_tick.js:68:7)
  | at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
  | at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
```

**Comment by rizzlinux1388** [comment]
Whoops, this *is* a duplicate of: [264](https://github.com/giggio/node-chromedriver/issues/264)
