### ISSUE TITLE
travis ci node install chromedriver 83 failed

### ISSUE THREAD

**Issue by june50232** [giggio/node-chromedriver#269]
localhost works fine but builded fail while running travis ci `node install.js` ~~ ><
travis ci error msg showed as below:

```
> chromedriver@83.0.0 install /home/travis/build/.../node_modules/chromedriver

466> node install.js
467
468internal/util.js:214
469 throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
470 ^
471
472TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
473 at promisify (internal/util.js:214:11)
474 at Object.<anonymous> (/home/travis/build/.../node_modules/extract-zip/index.js:11:18)
475 at Module._compile (module.js:653:30)
476 at Object.Module._extensions..js (module.js:664:10)
477 at Module.load (module.js:566:32)
478 at tryModuleLoad (module.js:506:12)
479 at Function.Module._load (module.js:498:3)
480 at Module.require (module.js:597:17)
481 at require (internal/module.js:11:18)
482 at Object.<anonymous> (/home/travis/build/.../node_modules/chromedriver/install.js:14:20)
```

**Comment by giggio** [comment]
Are you running an unsupported version of Node, like version 8? If so, it will not work with this library. Please see issue #260.
