### ISSUE TITLE
Error in dependencies to install chromedriver module in node!

### ISSUE THREAD

**Issue by Myky8** [giggio/node-chromedriver#279]
Steps to reproduce:

1. Run `yarn install` in node package.json project.

Dependecies error:

`error Couldn't find package "@testim/chrome-version@^1.0.7" required by "chromedriver@^83.0.1" on the "npm" registry.
Error: Couldn't find package "@nodelib/fs.walk@^1.2.3" required by "fast-glob@^3.0.3" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.4/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

**Comment by andrei-acuris** [comment]
can confirm, same thing happening while some tests run in docker. looking forward to a fix for this

**Comment by Myky8** [comment]
Seems that the module dependency with the error has been fixed! Now it installs correctly!
