### ISSUE TITLE
yarn install gets 400 bad request

### ISSUE THREAD

**Issue by jhoulu** [giggio/node-chromedriver#281]
Hi, I am running this on our Linux host:
`DETECT_CHROMEDRIVER_VERSION=true CHROMEDRIVER_FORCE_DOWNLOAD=true yarn install`

And got this error:
ChromeDriver installation failed { Error: Request failed with status code 400
at createError (/approot/Smile-Webserver/server/node_modules/axios/lib/core/createError.js:16:15)
at settle (/approot/Smile-Webserver/server/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/approot/Smile-Webserver/server/node_modules/axios/lib/adapters/http.js:236:11)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1143:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

Full Log:
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/5] ⢀ waiting...
[-/5] ⢀ waiting...
[3/5] ⢀ chromedriver
[-/5] ⢀ waiting...
error /approot/Smile-Webserver/server/node_modules/chromedriver: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /approot/Smile-Webserver/server/node_modules/chromedriver
Output:
Your Chrome version is 84.0.4147.105
Finding Chromedriver version.
ChromeDriver installation failed { Error: Request failed with status code 400
at createError (/approot/Smile-Webserver/server/node_modules/axios/lib/core/createError.js:16:15)
at settle (/approot/Smile-Webserver/server/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/approot/Smile-Webserver/server/node_modules/axios/lib/adapters/http.js:236:11)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1143:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
config:
{ url:
'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147',
method: 'get',
headers:

{ Accept: 'application/json, text/plain, */*', 'User-Agent': 'yarn/1.22.4 npm/? node/v10.17.0 linux x64', host: 'chromedriver.storage.googleapis.com' }
,
transformRequest: [ [Function: transformRequest] ],
transformResponse: [ [Function: transformResponse] ],
timeout: 0,
adapter: [Function: httpAdapter],
xsrfCookieName: 'XSRF-TOKEN',
xsrfHeaderName: 'X-XSRF-TOKEN',
maxContentLength: -1,
validateStatus: [Function: validateStatus],
httpsAgent:
Agent {
_events: [Object],
_eventsCount: 1,
_maxListeners: undefined,
defaultPort: 443,
protocol: 'https:',
options: [Object],
requests: {},
sockets: {},
freeSockets: {},
keepAliveMsecs: 1000,
keepAlive: false,
maxSockets: Infinity,
maxFreeSockets: 256,
maxCachedSessions: 100,
_sessionCache: [Object] },
data: undefined },
request:
ClientRequest {
_events:
[Object: null prototype]

{ socket: [Function], abort: [Function], aborted: [Function], error: [Function], timeout: [Function], prefinish: [Function: requestOnPrefinish] }
,
_eventsCount: 6,
_maxListeners: undefined,
output: [],
outputEncodings: [],
outputCallbacks: [],
outputSize: 0,
writable: true,
_last: true,
chunkedEncoding: false,
shouldKeepAlive: false,
useChunkedEncodingByDefault: false,
sendDate: false,
_removedConnection: false,
_removedContLen: false,
_removedTE: false,
_contentLength: 0,
_hasBody: true,
_trailer: '',
finished: true,
_headerSent: true,
socket:
Socket

{ connecting: false, _hadError: false, _handle: [TCP], _parent: null, _host: 'devproxy.company.com', _readableState: [ReadableState], readable: true, _events: [Object], _eventsCount: 7, _maxListeners: undefined, _writableState: [WritableState], writable: false, allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: null, _server: null, parser: null, _httpMessage: [Circular], [Symbol(asyncId)]: 22, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0 }
,
connection:
Socket

{ connecting: false, _hadError: false, _handle: [TCP], _parent: null, _host: 'devproxy.company.com', _readableState: [ReadableState], readable: true, _events: [Object], _eventsCount: 7, _maxListeners: undefined, _writableState: [WritableState], writable: false, allowHalfOpen: false, _sockname: null, _pendingData: null, _pendingEncoding: '', server: null, _server: null, parser: null, _httpMessage: [Circular], [Symbol(asyncId)]: 22, [Symbol(lastWriteQueueSize)]: 0, [Symbol(timeout)]: null, [Symbol(kBytesRead)]: 0, [Symbol(kBytesWritten)]: 0 }
,
_header:
'GET https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147 HTTP/1.1\r\nAccept: application/json, text/plain, /\r\nUser-Agent: yarn/1.22.4 npm/? node/v10.17.0 linux x64\r\nhost: chromedriver.storage.googleapis.com\r\nConnection: close\r\n\r\n',
_onPendingData: [Function: noopPendingOutput],
agent:
Agent {
_events: [Object],
_eventsCount: 1,
_maxListeners: undefined,
defaultPort: 80,
protocol: 'http:',
options: [Object],
requests: {},
sockets: [Object],
freeSockets: {},
keepAliveMsecs: 1000,
keepAlive: false,
maxSockets: Infinity,
maxFreeSockets: 256 },
socketPath: undefined,
timeout: undefined,
method: 'GET',
path:
'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147',
_ended: true,
res:
IncomingMessage {
_readableState: [ReadableState],
readable: false,
_events: [Object],
_eventsCount: 3,
_maxListeners: undefined,
socket: [Socket],
connection: [Socket],
httpVersionMajor: 1,
httpVersionMinor: 1,
httpVersion: '1.1',
complete: true,
headers: [Object],
rawHeaders: [Array],
trailers: {},
rawTrailers: [],
aborted: false,
upgrade: false,
url: '',
method: null,
statusCode: 400,
statusMessage: 'Bad Request',
client: [Socket],
_consuming: false,
_dumped: false,
req: [Circular],
responseUrl:
'http://devproxy.company.com:82/[https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147]',
redirects: [] },
aborted: undefined,
timeoutCb: null,
upgradeOrConnect: false,
parser: null,
maxHeadersCount: null,
_redirectable:
Writable

{ _writableState: [WritableState], writable: true, _events: [Object], _eventsCount: 2, _maxListeners: undefined, _options: [Object], _redirectCount: 0, _redirects: [], _requestBodyLength: 0, _requestBodyBuffers: [], _onNativeResponse: [Function], _currentRequest: [Circular], _currentUrl: 'http://devproxy.company.com:82/https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147' }
,
[Symbol(isCorked)]: false,
[Symbol(outHeadersKey)]:
[Object: null prototype]

{ accept: [Array], 'user-agent': [Array], host: [Array] }
},
response:
{ status: 400,
statusText: 'Bad Request',
headers:

{ 'cache-control': 'no-cache', pragma: 'no-cache', 'content-type': 'text/html; charset=utf-8', 'proxy-connection': 'close', connection: 'close', 'content-length': '691' }
,
config:

{ url: 'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147', method: 'get', headers: [Object], transformRequest: [Array], transformResponse: [Array], timeout: 0, adapter: [Function: httpAdapter], xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, validateStatus: [Function: validateStatus], httpsAgent: [Agent], data: undefined }
,
request:
ClientRequest

{ _events: [Object], _eventsCount: 6, _maxListeners: undefined, output: [], outputEncodings: [], outputCallbacks: [], outputSize: 0, writable: true, _last: true, chunkedEncoding: false, shouldKeepAlive: false, useChunkedEncodingByDefault: false, sendDate: false, _removedConnection: false, _removedContLen: false, _removedTE: false, _contentLength: 0, _hasBody: true, _trailer: '', finished: true, _headerSent: true, socket: [Socket], connection: [Socket], _header: 'GET https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: yarn/1.22.4 npm/? node/v10.17.0 linux x64\r\nhost: chromedriver.storage.googleapis.com\r\nConnection: close\r\n\r\n', _onPendingData: [Function: noopPendingOutput], agent: [Agent], socketPath: undefined, timeout: undefined, method: 'GET', path: 'https://chromedriver.storage.googleapis.com/LATEST_RELEASE_84.0.4147', _ended: true, res: [IncomingMessage], aborted: undefined, timeoutCb: null, upgradeOrConnect: false, parser: null, maxHeadersCount: null, _redirectable: [Writable], [Symbol(isCorked)]: false, [Symbol(outHeadersKey)]: [Object] }
,
data:
`'<HTML><HEAD>\n<TITLE>Request Error</TITLE>\n</HEAD>\n<BODY>\n<FONT face="Helvetica">\n<big><strong></strong></big><BR>\n</FONT>\n<blockquote>\n<TABLE border=0 cellPadding=1 width="80%">\n<TR><TD>\n<FONT face="Helvetica">\n<big>Request Error (invalid_request)</big>\n<BR>\n<BR>\n</FONT>\n</TD></TR>\n<TR><TD>\n<FONT face="Helvetica">\nYour request could not be processed. Request could not be handled\n</FONT>\n</TD></TR>\n<TR><TD>\n<FONT face="Helvetica">\nThis could be caused by a misconfiguration, or possibly a malformed request.\n</FONT>\n</TD></TR>\n<TR><TD>\n<FONT face="Helvetica" SIZE=2>\n<BR>\nFor assistance, contact your network support team.\n</FONT>\n</TD></TR>\n</TABLE>\n</blockquote>\n</FONT>\n</BODY></HTML>\n'` },

**Comment by jhoulu** [comment]
Following up. This error would go away without setting DETECT_CHROMEDRIVER_VERSION=true. However, the executables are missing under node_modules/chromedriver/lib

This only happens on our linux box. Building the same on PC would download the correct exe file.

**Comment by jhoulu** [comment]
More verbose logs from yarn:

Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
Downloading from file:  https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
Saving to file: /tmp/84.0.4147.30/chromedriver/chromedriver_linux64.zip
Error status code: 400
<HTML><HEAD>
<TITLE>Request Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Request Error (invalid_request)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
Your request could not be processed. Request could not be handled
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
This could be caused by a misconfiguration, or possibly a malformed request.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
