### ISSUE TITLE
npm install chromedriver give error

### ISSUE THREAD

**Issue by martinsangdo** [giggio/node-chromedriver#282]
Type "npm install", there is error:
> node ./download-chromedriver.js

internal/util.js:206
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:206:11)
    at Object.<anonymous> (/Users/sangdt/Documents/Source/Electron/webtorrent-desktop/node_modules/electron-chromedriver/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sangdt/Documents/Source/Electron/webtorrent-desktop/node_modules/electron-chromedriver/download-chromedriver.js:4:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@9.0.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@9.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
-----------
Tried 

My config:
npm --version: 5.5.1
node --version: v9.0.0

**Comment by balukov** [comment]
Is there any news about this?
There is a big issue to install webdriverio.
