### ISSUE TITLE
Cannot start chromedriver after upgrading to version 86.0.0

### ISSUE THREAD

**Issue by abilioesteves** [giggio/node-chromedriver#288]
Hello!

After Chrome updated to version 86.0.4240.80, I cannot get to start chromedriver version 86.0.0. 

I get the following error:

```
./node_modules/chromedriver/bin/chromedriver 
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn <my repo path>/node_modules/chromedriver/lib/chromedriver/chromedriver ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn <my repo path>/node_modules/chromedriver/lib/chromedriver/chromedriver',
  path: '<my repo path>/node_modules/chromedriver/lib/chromedriver/chromedriver',
  spawnargs: []
}
```

Is this a known issue? Should I just try to use an older version of Chrome/Chromium?

Context:
1. node version: v12.19.0
2. npm version: 6.14.8
3. OS: macOS Catalina v10.15.7
4. Have already cleared my npm cache and node_modules

Thank you for your support!

**Comment by abilioesteves** [comment]
Nevermind this issue. I had npm's `ignore-scripts` config set to `false`. Chromedriver is working fine with Chrome's new version.
