### ISSUE TITLE
Session not created with chromedriver 89.0.0

### ISSUE THREAD

**Issue by kranich** [giggio/node-chromedriver#306]
We can no longer run e2e tests in our CI pipeline after upgrading to version 89.0.0 (from 88.0.0) because the browser session is not created. The tests continue to work in our development environment. Our pipeline uses a headless Chrome on Linux, our development environment a non-headless Chrome on Windows.

We try to access our frontend on localhost port 4202

The (redacted) logs are as follows:

```
** Angular Live Development Server is listening on localhost:4202, open your browser on http://localhost:4202/XXX **
✔ Compiled successfully.
[07:40:53] I/launcher - Running 1 instances of WebDriver
[07:40:53] I/direct - Using ChromeDriver directly...
[07:50:54] E/launcher - session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: headless chrome=89.0.4389.82)
  (Driver info: chromedriver=89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}),platform=Linux 4.19.0-8-amd64 x86_64)
[07:50:54] E/launcher - SessionNotCreatedError: session not created
from timeout: Timed out receiving message from renderer: 600.000
  (Session info: headless chrome=89.0.4389.82)
  (Driver info: chromedriver=89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}),platform=Linux 4.19.0-8-amd64 x86_64)
    at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
    at node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebDriver.createSession()
    at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:769:24)
    at Function.createSession (node_modules/selenium-webdriver/chrome.js:761:15)
    at Direct.getNewDriver (node_modules/protractor/built/driverProviders/direct.js:77:33)
    at Runner.createBrowser (node_modules/protractor/built/runner.js:195:43)
    at node_modules/protractor/built/runner.js:339:29
    at _fulfilled (node_modules/protractor/node_modules/q/q.js:834:54)
    at node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (node_modules/protractor/node_modules/q/q.js:796:13)
    at node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (node_modules/protractor/node_modules/q/q.js:137:13)
[07:50:54] E/launcher - Process exited with error code 199
error Command failed with exit code 1.
```

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
