### ISSUE TITLE
Install is failing, npmconf errors

### ISSUE THREAD

**Issue by iameli** [giggio/node-chromedriver#38]
This appears to have started very recently, and I suspect it's in a dependency rather than Chromedriver itself, but I haven't quite been able to track it down yet so I figured I'd file here. This is on a completely empty fresh machine:

```
root@f4573f3a6074:/home# npm install chromedriver
npm WARN package.json home@1.0.0 No description
npm WARN package.json home@1.0.0 No repository field.
npm WARN package.json home@1.0.0 No README data
|
> chromedriver@2.19.0 install /home/node_modules/chromedriver
> node install.js


/home/node_modules/chromedriver/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210
    if (t && ((type.name && t.type.name) ?
                   ^
TypeError: Cannot read property 'name' of null
    at validate (/home/node_modules/chromedriver/node_modules/npmconf/node_modules/nopt/lib/nopt.js:210:20)
    at validate (/home/node_modules/chromedriver/node_modules/npmconf/node_modules/nopt/lib/nopt.js:179:11)
    at /home/node_modules/chromedriver/node_modules/npmconf/node_modules/nopt/lib/nopt.js:101:12
    at Array.map (native)
    at /home/node_modules/chromedriver/node_modules/npmconf/node_modules/nopt/lib/nopt.js:67:15
    at Array.forEach (native)
    at Function.clean (/home/node_modules/chromedriver/node_modules/npmconf/node_modules/nopt/lib/nopt.js:55:21)
    at /home/node_modules/chromedriver/node_modules/npmconf/npmconf.js:411:10
    at Array.forEach (native)
    at validate (/home/node_modules/chromedriver/node_modules/npmconf/npmconf.js:410:11)
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install" "chromedriver"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.19.0 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the chromedriver@2.19.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/npm-debug.log
root@f4573f3a6074:/home# npm --version
2.14.1
root@f4573f3a6074:/home# node --version
v0.10.40
root@f4573f3a6074:/home# 
```

**Comment by iameli** [comment]
Never mind, root problem is here. Cheers. https://github.com/npm/nopt/issues/54
