### ISSUE TITLE
chromedriver artifact arch has changed to `mac_arm64` from `mac64_m1`

### ISSUE THREAD

**Issue by sarkis** [giggio/node-chromedriver#384]
Looks like the latest chromedriver from google now has `mac_arm64` instead of `mac64_m1` as the arch. This can be seen searching for `106.0.5249.61/chromedriver_` here https://chromedriver.storage.googleapis.com/

```
❯ npm install chromedriver --no-save --detect_chromedriver_version

npm ERR! code 1
npm ERR! path /Users/svarozian/Projects/veza/cookieai-core/node_modules/chromedriver
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! Your Chrome version is 106.0.5249.61
npm ERR! Finding Chromedriver version.
npm ERR! Chromedriver version is 106.0.5249.61.
npm ERR! Compatible ChromeDriver version is 106.0.5249.61
npm ERR! Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
npm ERR! Downloading from file:  https://chromedriver.storage.googleapis.com/106.0.5249.61/chromedriver_mac64_m1.zip
npm ERR! Saving to file: /var/folders/f6/2pvgz0ls67d_dstpwmmfpj4h0000gp/T/106.0.5249.61/chromedriver/chromedriver_mac64_m1.zip
npm ERR! Error status code: 404
npm ERR! <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: chromedriver/106.0.5249.61/chromedriver_mac64_m1.zip</Details></Error>
npm ERR! ChromeDriver installation failed Error: Error with http(s) request: AxiosError: Request failed with status code 404
npm ERR!     at requestBinary (/Users/svarozian/Projects/veza/cookieai-core/node_modules/chromedriver/install.js:274:11)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async downloadFile (/Users/svarozian/Projects/veza/cookieai-core/node_modules/chromedriver/install.js:117:5)
npm ERR!     at async install (/Users/svarozian/Projects/veza/cookieai-core/node_modules/chromedriver/install.js:66:7)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svarozian/.npm/_logs/2022-09-28T17_53_36_774Z-debug-0.log
```

**Comment by segevmalool** [comment]
This is affecting me as well.
