### ISSUE TITLE
ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: unhandled inspector error:

### ISSUE THREAD

**Issue by xdsanzxd** [giggio/node-chromedriver#405]
Hello 

My automation scripts start to fails with the new chromedriver update v109

Here the error:
`ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: unhandled inspector error: {"code":-32000,"message":"Promise was collected"}`

Any idea to fix this issue?

here some logs

Thanks in advance

[0-2] 2023-01-24T18:15:18.243Z INFO webdriver: COMMAND findElement("css selector", ".open-free-text-itinerary-search .header-title")
[0-2] 2023-01-24T18:15:18.244Z INFO webdriver: [POST] 
[0-2] 2023-01-24T18:15:18.244Z INFO webdriver: DATA {
[0-2]   using: 'css selector',
[0-2]   value: '.open-free-text-itinerary-search .header-title'
[0-2] }
[1264:20912:0124/121520.444:ERROR:device_event_log_impl.cc(215)] [12:15:20.444] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[1264:20912:0124/121520.444:ERROR:usb_descriptors.cc(141)] Failed to read length for configuration 1.
[1264:20912:0124/121520.444:ERROR:usb_descriptors.cc(100)] Failed to read all configuration descriptors. Expected 2, got 1.
[1264:20912:0124/121520.445:ERROR:device_event_log_impl.cc(215)] [12:15:20.445] USB: usb_device_win.cc:96 Failed to read descriptors from \\?\usb#vid_0bda&pid_8153#000001#{a5dcbf10-6530-11d2-901f-00c04fb951ed}.
[1264:20912:0124/121520.445:ERROR:device_event_log_impl.cc(215)] [12:15:20.445] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[1264:20912:0124/121520.447:ERROR:device_event_log_impl.cc(215)] [12:15:20.447] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[1264:20912:0124/121520.447:ERROR:device_event_log_impl.cc(215)] [12:15:20.447] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[0-2] 2023-01-24T18:15:27.932Z WARN webdriver: Request failed with status 500 due to unknown error: unhandled inspector error: {"code":-32000,"message":"Promise was collected"}
[0-2]   (Session info: chrome=109.0.5414.75)
[0-2] 2023-01-24T18:15:27.933Z INFO webdriver: Retrying 1/1
[0-2] 2023-01-24T18:15:27.933Z INFO webdriver: [POST] http://localhost:9515/session/afc31e3ee61f28133e6d379e49198d50/element
[0-2] 2023-01-24T18:15:27.933Z INFO webdriver: DATA {
[0-2]   using: 'css selector',
[0-2]   value: '.open-free-text-itinerary-search .header-title'
[0-2] }
[0-2] 2023-01-24T18:15:28.318Z **ERROR webdriver: Request failed with status 500 due to unknown error: unknown error: unhandled inspector error: {"code":-32000,"message":"Promise was collected"}**
[0-2]   (Session info: [chrome=109.0.5414.75)
[0-2] Error in "0: When the customer search a cruise from"
unknown error: unknown error: unhandled inspector error: {"code":-32000,"message":"Promise was collected"}
  (Session info: **chrome=109.0.5414.75)**
    at getErrorFromResponseBody (C:\cel-wdio-web\node_modules\webdriver\build\utils.js:198:12)
    at NodeJSRequest._request (C:\cel-wdio-web\node_modules\webdriver\build\request\index.js:166:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Browser.wrapCommandFn (C:\cel-wdio-web\node_modules\@wdio\utils\build\shim.js:137:29)
    at async Browser.$ (C:\cel-wdio-web\node_modules\webdriverio\build\commands\browser\$.js:91:17)
    at async Browser.wrapCommandFn (C:\cel-wdio-web\node_modules\@wdio\utils\build\shim.js:137:29)
    at async HomePage.FindACrusie (C:\cel-wdio-web\features\pageobjects\homePage.ts:148:16)
    at async World.<anonymous> (C:\cel-wdio-web\features\step-definitions\homeSteps.ts:21:5)
[0-2] 2023-01-24T18:15:28.343Z INFO webdriver: COMMAND deleteSession()

**Comment by giggio** [comment]
This is a Chromedriver issue, not an issue with this npm package, that only installs Chromedriver. Please direct it to the Chromedriver team on their [issue tracker](http://chromedriver.chromium.org/help).
