### ISSUE TITLE
chromedriver download 404s

### ISSUE THREAD

**Issue by michaelficarra** [giggio/node-chromedriver#478]
```
npm ERR! code 1
npm ERR! path /Users/[redacted]/node_modules/chromedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Your Chrome version is 125.0.6422.61
npm ERR! Finding Chromedriver version.
npm ERR! Chromedriver version is 125.0.6422.141.
npm ERR! Compatible ChromeDriver version is 125.0.6422.141
npm ERR! Saving to file: /var/folders/rf/vyh33z4n6v71rhhn6p45jl200000gp/T/125.0.6422.141/chromedriver/chromedriver-mac-x64.zip
npm ERR! Current existing ChromeDriver binary is unavailable, proceeding with download and extraction.
npm ERR! Downloading from file:  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/125.0.6422.141/mac-x64/chromedriver-mac-x64.zip
npm ERR! Error status code: 404
npm ERR!
npm ERR! <!DOCTYPE html>
npm ERR! <html lang=en>
npm ERR!   <meta charset=utf-8>
npm ERR!   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
npm ERR!   <title>Error 404 (Not Found)!!1</title>
npm ERR!   <style>
npm ERR!     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
npm ERR!   </style>
npm ERR!   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
npm ERR!   <p><b>404.</b> <ins>That’s an error.</ins>
npm ERR!   <p>  <ins>That’s all we know.</ins>
npm ERR!
npm ERR! ChromeDriver installation failed Error: Error with http(s) request: AxiosError: Request failed with status code 404
npm ERR!     at requestBinary (/Users/[redacted]/node_modules/chromedriver/install.js:336:11)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR!     at async downloadFile (/Users/[redacted]/node_modules/chromedriver/install.js:134:7)
npm ERR!     at async install (/Users/[redacted]/node_modules/chromedriver/install.js:67:7)

npm ERR! A complete log of this run can be found in: /Users/[redacted]/.npm/_logs/2024-06-06T04_31_02_878Z-debug-0.log
```

**Comment by giggio** [comment]
You are using an older version of this package. The Chromedriver team changed the download URLs, so you need to update the package to be able to get the Chromedriver binaries.
See Chrome for testing to know more: https://googlechromelabs.github.io/chrome-for-testing/
Also: https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE
And: https://github.com/giggio/node-chromedriver#custom-binaries-url
This started with version 115.
Related issue: #448.

**Comment by michaelficarra** [comment]
Thanks @giggio. Have you considered marking the affected versions as deprecated so that a user would get a warning on the console and try upgrading before posting here?

**Comment by giggio** [comment]
No, but that is a good idea. I'll do it.
