### ISSUE TITLE
couldn't install this with node(v6.9.1) and npm(v3.10.9)

### ISSUE THREAD

**Issue by libchaos** [giggio/node-chromedriver#73]
```
306 verbose stack Error: chromedriver@2.25.1 install: `node install.js`
2306 verbose stack Exit status 1
2306 verbose stack     at EventEmitter.<anonymous> (/Users/mac/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
2306 verbose stack     at emitTwo (events.js:106:13)
2306 verbose stack     at EventEmitter.emit (events.js:191:7)
2306 verbose stack     at ChildProcess.<anonymous> (/Users/mac/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
2306 verbose stack     at emitTwo (events.js:106:13)
2306 verbose stack     at ChildProcess.emit (events.js:191:7)
2306 verbose stack     at maybeClose (internal/child_process.js:877:16)
2306 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2307 verbose pkgid chromedriver@2.25.1
2308 verbose cwd /Users/mac
2309 error Darwin 16.1.0
2310 error argv "/Users/mac/.nvm/versions/node/v6.9.1/bin/node" "/Users/mac/.nvm/versions/node/v6.9.1/bin/npm" "install" "-g" "chromedriver" "--chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver"
2311 error node v6.9.1
2312 error npm  v3.10.9
2313 error code ELIFECYCLE
2314 error chromedriver@2.25.1 install: `node install.js`
2314 error Exit status 1
2315 error Failed at the chromedriver@2.25.1 install script 'node install.js'.
```

**Comment by atif089** [comment]
+1

**Comment by giggio** [comment]
the taobao.org mirror is broken. see #67.
