### ISSUE TITLE
Install fails on bash for windows

### ISSUE THREAD

**Issue by sschimmel** [giggio/node-chromedriver#75]
Installing chromedriver using npm on bash for Windows fails with the following output.

```
sebastiaan@DESKTOP-7TBVMQO:/.../$ npm install chromedriver
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> chromedriver@2.25.1 install /.../node_modules/chromedriver
> node install.js

/.../node_modules/npmconf/config-defs.js:332
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^

Error: EINVAL: invalid argument, uv_interface_addresses
    at Error (native)
    at getLocalAddresses (/.../node_modules/npmconf/config-defs.js:332:18)
    at Object.<anonymous> (/.../node_modules/npmconf/config-defs.js:281:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by giggio** [comment]
This is a known problem in the current version of the WSL. This is not a problem with the package itself.
